"""add_role_to_users

Revision ID: 0737d0b6ff51
Revises: f7d01a2b5aa0
Create Date: 2026-06-09 14:42:56.587242

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0737d0b6ff51'
down_revision: Union[str, Sequence[str], None] = 'f7d01a2b5aa0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
    'users',
    sa.Column(
        'role',
        sa.String(),
        nullable=False,
        server_default='user'
    )
)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    # ### end Alembic commands ###
